select
  (select count(*) from information_schema.tables where table_schema = 'public' and table_name in (
    'system_permissions',
    'platform_role_permission_policies',
    'club_position_permission_policies',
    'department_role_permission_policies',
    'user_permission_overrides',
    'user_permission_override_history',
    'approval_requests',
    'approval_request_actions',
    'staff_invitations',
    'staff_invitation_department_scopes'
  )) as cm4_table_count,
  (select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relname in (
    'system_permissions',
    'platform_role_permission_policies',
    'club_position_permission_policies',
    'department_role_permission_policies',
    'user_permission_overrides',
    'user_permission_override_history',
    'approval_requests',
    'approval_request_actions',
    'staff_invitations',
    'staff_invitation_department_scopes'
  ) and c.relrowsecurity) as cm4_rls_table_count,
  (select count(*) from public.system_permissions where is_active = true) as active_permission_count,
  (select count(*) from public.platform_role_permission_policies where is_active = true) as platform_policy_count,
  (select count(*) from public.club_position_permission_policies where is_active = true) as position_policy_count,
  (select count(*) from public.department_role_permission_policies where is_active = true) as department_policy_count,
  (select count(*) from pg_indexes where schemaname = 'public' and indexname = 'volunteer_department_memberships_one_active_head_idx') as one_head_constraint_count,
  (select count(*) from pg_indexes where schemaname = 'public' and indexname = 'volunteer_department_memberships_one_active_deputy_idx') as one_deputy_constraint_count,
  (select count(*) from public.volunteer_department_memberships where department_role in ('volunteer', 'coordinator')) as legacy_department_role_count,
  (select count(*) from public.volunteer_platform_roles where role = 'super_admin' and status = 'active') as active_super_admin_count,
  (select count(*) from public.volunteer_club_positions vcp join public.club_positions cp on cp.id = vcp.club_position_id where cp.slug = 'general-secretary' and vcp.status = 'active' and vcp.is_primary = true) as active_primary_general_secretary_count,
  (select count(*) from public.volunteer_department_memberships) as department_membership_count,
  (select count(*) from public.staff_invitations) as staff_invitation_count,
  (select count(*) from public.blood_donor_profiles) as blood_donor_count,
  (select count(*) from public.blood_requests) as blood_request_count,
  (select count(*) from public.blood_matches) as blood_match_count,
  (select count(*) from public.blood_donations) as blood_donation_count,
  (select count(*) from public.blood_support_settings where setting_key in ('public_request_intake_enabled', 'public_donor_interest_enabled') and setting_value = 'false'::jsonb and is_active = true) as disabled_blood_public_intake_count,
  (select count(*) from public.events where status = 'published') as published_events,
  (select count(*) from public.notices where status = 'published') as published_notices,
  (select count(*) from public.gallery_items where status = 'published') as published_gallery_items,
  (select count(*) from information_schema.role_table_grants where table_schema = 'public' and table_name in ('system_permissions','user_permission_overrides','approval_requests','staff_invitations') and grantee = 'anon') as anon_internal_grant_count,
  (select count(*) from information_schema.role_table_grants where table_schema = 'public' and table_name in ('system_permissions','user_permission_overrides','approval_requests','staff_invitations') and grantee = 'authenticated' and privilege_type in ('INSERT','UPDATE','DELETE')) as authenticated_internal_write_grant_count;
